### PR TITLE
Enable Linux Plugin build.

### PR DESCRIPTION
**Pull request by KottV**
This just enables Linux target in plugins .jucer.
Works for me at least.

### CODE REVIEW

**Comment by apohl79** [comment]
Thx for this. I will setup a linux build env and test this patch.

**Comment by apohl79** [comment]
OK setting up the linux ENV is less straight forward than expected. What distro are you building on and which deps are required? My initial thought was to take the latest ubuntu lts, but that does not work for me.

**Comment by KottV** [comment]
I use openSUSE and have own repository with JUCE stuff https://www.opensuse.org/ repo: https://build.opensuse.org/project/show/home:kill_it:JUCE
I can write brief howto.

Or if you still have Ubuntu you may simple install juce-modules-source and juce-tools to satisfy dependencies. After that you can download and use original JUCE.

**Comment by apohl79** [comment]
Got it working thx.

**Comment by apohl79** [comment]
First of all, your patch works. I can build and load the VST plugin into ardour. But I'm having issues with ffmpeg and libwebp as libwebp on ubuntu is pretty old seems to have decoding problems, as I'm using a much newer version on windows and OSX. But as ardour links against ffmpeg too, I can't easily replace the lib versions. Also, I can't link all these libs statically into the AG VST/VST3 shared libs.

... so still working on it.

**Comment by KottV** [comment]
I see.
What's Ubuntu's version do you have? I have vms with 20.04 and 18.04 so I may take a look too.

**Comment by apohl79** [comment]
20.04. The libwebp version that ships with it is 0.6. The current version is 1.1.

Anyways, legacy screen capturing works and seems stable. 

I will add mjpeg support to the ffmpeg code. Using this will work than on a linux client, as jpeg support is directly included in JUCE.

**Pull request merged**
